import { Orbitron } from "next/font/google";
import "./globals.css";
import { Footer } from "./components/Footer";
import Header from "./components/Nave/Header";

// const inter = Inter({ subsets: ["latin"] });

const Orbitron_init = Orbitron({
  subsets:["latin"],
  weight:['400', '500' , '600' , '700' , '800' , '900'],
  variable: '---font-orbitron',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={Orbitron_init.variable}>
        <Header />
        {children}
        <Footer />
      </body>
      
    </html>
  );
}
